update

diff --git a/train_finetune_llm/script_qlora b/train_finetune_llm/script_qlora
--- a/train_finetune_llm/script_qlora
+++ b/train_finetune_llm/script_qlora
@@ -1,7 +1,7 @@
 #!/bin/bash
 #SBATCH --job-name=test_slurm # define job name
 #SBATCH --nodes=1             # define node
-#SBATCH --gpus-per-node=1    # define gpu limmit in 1 node
+#SBATCH --gpus-per-node=2    # define gpu limmit in 1 node
 #SBATCH --ntasks=1           # define number tasks
 #SBATCH --cpus-per-task=24   # There are 24 CPU cores
 #SBATCH --nodelist=node002
@@ -11,7 +11,7 @@
 
 # while true; do nvidia-smi > gpu_status.txt; sleep 5; done &
 # while true; do nvidia-smi > gpu_status.txt; sleep 5; done &
-# nvidia-smi
+nvidia-smi
 nvidia-smi --query-gpu=timestamp,utilization.gpu,utilization.memory,memory.total,memory.free,memory.used --format=csv -l 120 >> ${SLURM_JOB_ID}_gpu_usage.log &
 
 echo "-----------------------------"
@@ -22,7 +22,8 @@ export FSDP_CPU_RAM_EFFICIENT_LOADING=1
 
 
 # Execute the Python script using torchrun for distributed training
-python unsloth_sft_finetune.py || echo "Python script failed with exit code $?"
+# accelerate launch --main_process_port 12345 Qlora_finetuning.py  --ddp_find_unused_parameters False || echo "Python script failed with exit code $?"
+accelerate launch --main_process_port 29002  Qlora_finetuning.py  --ddp_find_unused_parameters False || echo "Python script failed with exit code $?"
 
 
 echo "-----------------------------"
